<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <ProjectReference Include="..\VkoMonitoring.Agent.Core\VkoMonitoring.Agent.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Persistence\Sql\001_initial_schema.sql" />
  </ItemGroup>
</Project>
